### ISSUE TITLE
suggestion: add more info in readme.md about installing Python and Pip

### ISSUE THREAD

**Issue by ForrestTrepte** [eddex/thefuck-windows#2]
Thank you for helping Windows users take advantage of this tool!

For those of us who aren't already knowledgeable about the Python environment, this may be insufficient to get us going:
Prequisites: [install python and pip](https://www.python.org)

There's a lot of information on the python.org page on getting started as a Python developer, but it isn't immediately clear exactly what the shortest set of steps would be just to install it and get it configured if all I care about right now is getting going with thefuck.

It would be nice to have garden path instructions (or setup in the scripts) for a Windows user on a clean machine for installing Python/pip and getting thefuck running in Powershell.

For me, personally, I think I actually already have Python and pip installed. I can run pip from my Anaconda Prompt. But I don't know how to configure this environment to run inside PowerShell and based on [this issue](https://github.com/ContinuumIO/anaconda-issues/issues/311) it sounds difficult/experimental to do so.

**Comment by eddex** [comment]
Hi Forrest

Thanks for the comment. The only thing needed for the script in this repo to work is pip, the python package manager. It is used to download the `thefuck` package from PyPi (https://pypi.org/project/thefuck/).

As for your setup: Unfortunately I'm not very familiar with Anaconda but I know that you can activate an Anaconda environment in Powershell. Here's some more information: https://stackoverflow.com/questions/47800794/how-to-activate-different-anaconda-environment-from-powershell

If you want to install Python without Anaconda, you can download the latest version from the official site: [https://www.python.org/downloads/release/python-382/](https://www.python.org/downloads/release/python-382/). You can find the _Windows x86-64 executable installer_ at the bottom of the page.

Hope this helps.
Cheers!

**Comment by ForrestTrepte** [comment]
Thanks @eddex 
Adding Anaconda to my path as described in your link set up pip, and then the install-powershell.ps1 worked great!
